version: '3.8'

services:
  test_web:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    depends_on:
      - test_postgres
      - test_redis
    env_file:
      - .env
    environment:
      - DB_HOST=${TEST_DB_HOST}
      - DB_PORT=${TEST_DB_PORT}
      - DB_NAME=${TEST_DB_NAME}
      - DB_USER=${TEST_DB_USER}
      - DB_PASS=${TEST_DB_PASS}
      - REDIS_HOST=${TEST_REDIS_HOST}
    volumes:
      - ./src/web/tests:/project/tests
    entrypoint: ''
    command: [ 'pytest', 'tests/' ]

  test_postgres:
    image: postgres:17
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${TEST_DB_NAME}
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASS}

  test_redis:
    image: redis:8-alpine
    command: [ 'redis-server', '--maxmemory', '100mb', '--maxmemory-policy', 'allkeys-lru' ]
