version: '3.8'

services:
  postgres:
    image: postgres:17
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data:
