version: '3.8'

services:
  parser:
    build:
      context: ./src/parser
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env

  web:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: ./src/web
          target: /project

  postgres:
    image: postgres:17
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    command: [ 'redis-server', '--maxmemory', '100mb', '--maxmemory-policy', 'allkeys-lru' ]



volumes:
  pg_data:
